### ISSUE TITLE
why not webkeys? i.e. https URIs?

### ISSUE THREAD

**Issue by dckc** [capabilityio/capability-uri#2]
ref [web-key](http://waterken.sourceforge.net/web-key/)

also:
> Marc Stiegler came up with a neat idea, bookmarkable OAuth tokens.  The idea is to transmit the secret in the HTTP header but show it in the address bar as part of the URL, so it can be bookmarked. 
 -- [to cap-talk Feb 7, 2020](https://groups.google.com/forum/#!searchin/cap-talk/oauth$20bookmark%7Csort:date/cap-talk/n6yDX1Fzvz0/ScM3xi3bAQAJ)

**Comment by dckc** [comment]
p.s. [in your Austin node.js meetup talk](https://youtu.be/I-jkjj62jTw?t=454), you say OAuth asks "Who are you?" but harder... I suppose that's the way it's used in most implementations, but it's possible to use it capability style, as Stiegler points out, no?

**Comment by tristanls** [comment]
It's been so long that I'm surprised I actually found an answer to why not web keys :) 

A while back (~2013), it seems I worked on a [never published] document called "Beyond Fielding's REST: RESTful Capabilities", where I came up with a justification for an `httpc` (HTTP Capabilities) scheme. web-keys were source material for that document.

Here's the excerpts that hopefully explain the difference (HTTPC and CAPABILITY methods referenced below are ideas that eventually ended up as `cpblty` scheme):

>This post introduces the HTTPC scheme and an associated CAPABILITY method. This alternative is proposed by means of an exploration into reformulating REST in terms of Object Capabilities[ocap] by disallowing representation of resources using identifiers and choosing to use capabilities instead. Using capabilities on the Web is not a new idea. Web-keys, which reify capabilities in a Web context, have been introduced back in 2007[web-key]. The discussion here will copy and borrow heavily from web-keys and explain the proposed RESTful Capabilities in the context of Fielding’s REST. Where there seem to be no significant differences between the two, the similarities will not be addressed unless they are relevant to the discussion.
>
>**Difference between REST and RESTful Capabilities**
>
>> REST is defined by four interface constraints: identification of resources; manipulation of resources through representations; self-descriptive messages; and, hypermedia as the engine of application state.[REST#ch5]
>
>To contrast with Fielding’s REST definition:
>
>> RESTful Capabilities are defined by four interface constraints: identification of capabilities; manipulation of resources through capabilities; self-descriptive messages; and, hypermedia as the engine of application state.
>
> **Resources and Resource ~~Identifiers~~ Capabilities**
>
> In Fielding’s REST formulation, the key abstraction of information is a resource, which can be mapped onto resource representations and/or resource identifiers[REST#ch5]. In a RESTful Capabilities formulation, we can still map resources onto resource representations, however, instead of identifiers we allow only resource capabilities as the other possible mapping type. A helpful way to appreciate the difference between the formulations is that instead of thinking about “things”, we think about “what can be done (to things).”
>
>Fielding gives, as an example of resources, the “author’s preferred version” of an academic paper whose value changes over time, and “the paper published in the proceedings of conference X” which is a static value. In contrast, a RESTful Capabilities would give “capability to view author’s preferred version”, “capability to delete author’s preferred version”, “capability to edit author’s preferred version”. Similarly, we would have “capability to view the paper published in the proceedings of conference X”, but probably not a capability to delete or edit it as it is meant to be a static resource. Since no other changes are necessary, with a RESTful Capabilities formulation, we still have the advantages of Fielding’s REST such as generality, late binding of the reference to representation, and referencing the concept (via capabilities). Notice that we can share the “capability to view author’s preferred version” without sharing the capability to delete or edit, more on this later.
>
> It is worth highlighting that this is an area where RESTful Capabilities differ from a web-key implementation. Web-keys seem to assume that resource identifiers are representations of a resource[web-key] (as in REST), and a user resource could be accessed using a web-key as an authentication token similar to:
> 
>```
>https://mail.example.com/user123/#mhbqcmmva5ja3
>```
> 
> However, a RESTful Capability access to such a resource would be opaque because identifying a resource by an identifier such as user123 does not fit within RESTful Capability constraints. RESTful Capability analog to the above would look like more this:
> 
>```
> https://mail.example.com/#mhbqcmmva5ja3
>``` 
> _Note: the exact format will be introduced later, the scheme is different and the actual capability would be considerably longer but this example is intended to highlight only the difference being pointed out._
>
> References:
> - [REST#ch5] Roy Thomas Fielding: Architectural Styles and the Design of Network-based Software Architectures, Chapter 5, Representational State Transfer (REST). University of California, Irvine, 2000. http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm. Accessed on 28 Oct 2013.
> - [web-key] Tyler Close: Mashing with permission. 2007. http://waterken.sourceforge.net/web-key/. Accessed on 29 Oct 2013.

**Comment by tristanls** [comment]
> but it's possible to use [OAuth] capability style, as Stiegler points out, no?

Absolutely. That's how `cpblty` scheme is implemented on top of HTTPS, [the capability is sent as a `Bearer` token in `Authorization` header](https://github.com/capabilityio/capability-sdk-js/blob/master/index.js#L77).

**Comment by dckc** [comment]
> ...
> > It is worth highlighting that this is an area where RESTful Capabilities differ from a web-key implementation. Web-keys seem to assume that resource identifiers are representations of a resource[web-key] (as in REST),

identifiers are representations? I don't know how to make sense of that. A representation is what you get back from a GET request. And identifier is just a way to refer to a resource.

> and a user resource could be accessed using a web-key as an authentication token similar to:
> > ```
> > https://mail.example.com/user123/#mhbqcmmva5ja3
> > ```
> > 
> > 
> > However, a RESTful Capability access to such a resource would be opaque because identifying a resource by an identifier such as user123 does not fit within RESTful Capability constraints.

Again, this makes my head hurt; RESTful Capability constraints bind on the syntax of identifiers? how / why?

> > RESTful Capability analog to the above would look like more this:
> > ```
> > https://mail.example.com/#mhbqcmmva5ja3
> > ```

Using non-trivial path components somehow violates constraints? Doesn't all the work with webkeys clearly demonstrate that this is not so?

“capability to edit author’s preferred version” vs "author’s preferred version" is expressed in the fragment after the `#`; i.e. it "... may be some portion or subset of the primary resource, some view on representations of the primary resource, or some other resource defined or described by those representations." [section 3.5 Fragment of RFC3896](https://tools.ietf.org/html/rfc3986#section-3.5)

**Comment by tristanls** [comment]
>identifier is just a way to refer to a resource

Right, an object capability combines designation of a resource with the action to take on the resource. The two are inseparable. I diverged from web key because the identifier (resource designation) is explicit and I wanted to see what it would look like if identifier and authority for action were not possible to describe separately from each other.

Having a URI like `https://mail.example.com/user123/#mhbqcmmva5ja3`, allows me to make up URIs like `https://mail.example.com/user123/#dfhayy3343` or `https://mail.example.com/user123/#07373371111`. I am designating a resource and guessing authority. I wanted to explicitly not do that and ensure that resource designation is always inseparable from authority. Hence using a URI like `https://mail.example.com/#mhbqcmmva5ja3`, where the fragment `#mhbqcmmva5ja3` designates the resource and authority to take action indivisibly.

For what its worth, with the above setup where resource designation and authority are indivisible, I did find a convenient use for the non-fragment path component of the URI. It can be used to encode meaning for the holder of the capability, like a pet name:
```
cpblty://mail.example.com/dansworkemail?type=readonly#mhbqcmmva5ja3
```
`dansworkemail?type=readonly` would never be sent to `mail.example.com`, but it can be bookmarked by me and is meaningful to me, the capability holder.

**Comment by dckc** [comment]
Well, it seems like unmotivated complexity that will get in the way of adoption, which would be a shame. So I wish you'd use webkeys. But time will tell. Good luck.

**Comment by tristanls** [comment]
Looking at the number of words I provided in this thread, I don't think "unmotivated" is an accurate description. I interpret your comment as statement that the provided motivation does not justify an introduction of an entirely separate URI scheme.

Thanks for getting me to document publicly the reasons behind the scheme, even if they didn't end up convincing you :)

**Comment by dckc** [comment]
right... insufficiently motivated for a separate URI scheme is what I meant.
